# Generated by Django 5.2 on 2026-01-31 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventmodel_address_eventmodel_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatedmembermodel',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gym_participated', to='api.gymmodel'),
        ),
    ]
