# Generated by Django 5.2 on 2026-02-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_participatedmembermodel_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='participation_amount',
            field=models.IntegerField(default=0),
        ),
    ]
