# Generated by Django 5.2 on 2026-02-02 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_eventmodel_participation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentordermodel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_order', to='api.eventmodel'),
        ),
        migrations.AddField(
            model_name='paymentordermodel',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_order', to='api.membermodel'),
        ),
    ]
