# Generated by Django 5.2 on 2026-02-02 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_paymentordermodel_event_paymentordermodel_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentordermodel',
            name='participate_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participated_member_order', to='api.participatedmembermodel'),
        ),
    ]
