# Generated by Django 5.2 on 2026-02-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_paymentordermodel_participate_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentordermodel',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
