# Generated by Django 5.2 on 2026-02-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sponsormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsormodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
