# Generated by Django 4.2.11 on 2026-02-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sponsormodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
