# Generated by Django 4.2.11 on 2026-02-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_membermodel_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membermodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='membermodel',
            name='registration_type',
            field=models.CharField(choices=[('gym_member', 'Gym Member'), ('individual', 'Independent / Individual')], default='individual', help_text='Whether this member is part of a gym or registering independently', max_length=20),
        ),
        migrations.AddField(
            model_name='participatedmembermodel',
            name='registration_type',
            field=models.CharField(choices=[('gym_member', 'Gym Member'), ('individual', 'Independent / Individual')], default='gym_member', help_text='Registration type at the time of participation', max_length=20),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text="Participant's gender (optional)", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='gym',
            field=models.ForeignKey(blank=True, help_text='Gym this member belongs to (null for independent participants)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_members', to='api.gymmodel'),
        ),
        migrations.AlterField(
            model_name='participatedmembermodel',
            name='gym',
            field=models.ForeignKey(blank=True, help_text='Gym of the participant (copied from MemberModel for faster queries / historical data)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_participated', to='api.gymmodel'),
        ),
    ]
