# Generated by Django 4.2.11 on 2026-02-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_membermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participatedmembermodel',
            name='registration_type',
            field=models.CharField(choices=[('gym_member', 'Gym Member'), ('individual', 'Independent / Individual')], default='individual', help_text='Registration type at the time of participation', max_length=20),
        ),
    ]
