# Generated by Django 4.2.11 on 2026-02-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_participatedmembermodel_registration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='gym',
            field=models.ForeignKey(blank=True, help_text='Gym this member belongs to (null for independent participants)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_member', to='api.gymmodel'),
        ),
    ]
