# Generated by Django 5.2 on 2026-04-16 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_referusermodel_participatedmembermodel_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_members', to='api.referusermodel'),
        ),
    ]
