# Generated by Django 5.2 on 2026-04-19 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_membermodel_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('registration_type', models.CharField(choices=[('gym', 'Gym Participant'), ('individual', 'Individual')], max_length=20)),
                ('titan_id_input', models.CharField(blank=True, max_length=20, null=True)),
                ('event_leg', models.CharField(choices=[('mumbai', 'Mumbai May 23'), ('delhi', 'Delhi Sep 19'), ('bengaluru', 'Bengaluru Feb 6')], max_length=50)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_confirmed_by_employee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='GOTEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('event_leg', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('coach', 'Head Coach'), ('other', 'Other')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('active_members', models.CharField(max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_athletes', models.CharField(max_length=50)),
                ('event_leg', models.CharField(choices=[('mumbai', 'Mumbai May 23'), ('delhi', 'Delhi Sep 19'), ('bengaluru', 'Bengaluru Feb 6')], max_length=50)),
                ('titan_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_mpcg', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_confirmed_by_employee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('got_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gotemployee')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=1999, max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('success', 'Success'), ('failed', 'Failed')], default='created', max_length=20)),
                ('gateway_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('refer_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('gateway_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='participatedmembermodel',
            name='event',
        ),
        migrations.RemoveField(
            model_name='paymentordermodel',
            name='event',
        ),
        migrations.RemoveField(
            model_name='referusermodel',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='participatedmembermodel',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='membermodel',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='membermodel',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='participatedmembermodel',
            name='member',
        ),
        migrations.RemoveField(
            model_name='paymentordermodel',
            name='member',
        ),
        migrations.RemoveField(
            model_name='participatedmembermodel',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='paymentordermodel',
            name='participate_member',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='order',
        ),
        migrations.DeleteModel(
            name='SponsorModel',
        ),
        migrations.AddField(
            model_name='athlete',
            name='got_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gotemployee'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='related_gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gym'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gym'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.athlete'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paymentorder'),
        ),
        migrations.DeleteModel(
            name='EventModel',
        ),
        migrations.DeleteModel(
            name='GymModel',
        ),
        migrations.DeleteModel(
            name='MemberModel',
        ),
        migrations.DeleteModel(
            name='ReferUserModel',
        ),
        migrations.DeleteModel(
            name='ParticipatedMemberModel',
        ),
        migrations.DeleteModel(
            name='PaymentOrderModel',
        ),
        migrations.DeleteModel(
            name='TransactionModel',
        ),
    ]
