# Generated by Django 5.2 on 2026-04-19 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_athlete_emaillog_gotemployee_gym_paymentorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_leg', models.CharField(max_length=50)),
                ('season', models.CharField(default='S1', max_length=20)),
                ('tracking_id', models.CharField(max_length=20, unique=True)),
                ('payment_status', models.CharField(max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.athlete')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gym')),
            ],
        ),
    ]
