# Generated by Django 5.2 on 2026-04-19 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='participation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.participation'),
        ),
    ]
