"""
Django settings for titan_api_proj project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'import_export',

    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ────────────────────────────────────────────────
#           REST FRAMEWORK + SIMPLE JWT
# ────────────────────────────────────────────────

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Optional - good defaults for production
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    # How long access token lives (short!)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # ← most common in 2025

    # Refresh token lifetime (much longer)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # or 30 days

    # Very important for mobile & SPA apps
    'ROTATE_REFRESH_TOKENS': True,  # old refresh token becomes invalid after use
    'BLACKLIST_AFTER_ROTATION': True,  # blacklist old refresh tokens

    'AUTH_HEADER_TYPES': ('Bearer',),

    # Optional: better security in production
    'SIGNING_KEY': 'your-very-long-secret-key-keep-it-safe',  # better use env variable!

    # Optional: good for mobile apps
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    # Optional: include more user data in token
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
}

ROOT_URLCONF = 'titan_api_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'titan_api_proj.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME'),  # Name of your database
        'USER': config('DB_USER'),  # Your MySQL username
        'PASSWORD': config('DB_PASSWORD'),  # Your MySQL password
        'HOST': config('DB_HOST'),  # Host of your MySQL database (use 'localhost' for local MySQL)
        'PORT': config('DB_PORT'),  # Default MySQL port
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # if you have project-level static
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

WHITENOISE_MANIFEST_STRICT = False          # ← prevents 500 if file missing from manifest
WHITENOISE_ALLOW_ALL_ORIGINS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = 465
EMAIL_USE_SSL = True  # Note: Use SSL instead of TLS for port 465
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # Replace with the actual password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Cashfree config
CASHFREE_CLIENT_ID = config('CASHFREE_TEST_API_KEY')
CASHFREE_CLIENT_SECRET = config('CASHFREE_TEST_SECRET_KEY')
CASHFREE_ENV = 'SANDBOX'  # change to "PROD" later
CASHFREE_API_VERSION = "2025-01-01"  # most current in 2026

# Very important for redirect after payment
# For local development
CASHFREE_RETURN_URL = "http://127.0.0.1:8000/api/v1/payment/success/?order_id={order_id}"
CASHFREE_NOTIFY_URL = "http://127.0.0.1:8000/api/v1/webhooks/cashfree/"
